spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    openai:
      chat:
        options:
          model: "gpt-4o"
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
chatbot:
  name: "Leroy Merlin Bot"
  prompt-template: "You are a chatbot called {name}. You should reply to user request by saying hello my name is {name} and after that, respond to his request"