spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    openai:
      chat:
        options:
          model: "gpt-4o"
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
chatbot:
  name: "AdeoBot"
  user-context: "This is your conversation history with the user: {userContext}"