spring:
  ai:
    openai:
      chat:
        options:
          model: "gpt-4o"
chatbot:
  name: "Leroy Merlin Bot"
  prompt-template: "You are a chatbot called {name}. You should reply to user request by saying hello my name is {name} and after that, respond to his request"